### ISSUE TITLE
marks and punctuation pecularities

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/AmaticSC#5]
`commaturnedabovecomb` inconsistent in Condensed and Bold Condensed:
<img width="441" alt="screen shot 2017-10-21 at 1 12 02 pm" src="https://user-images.githubusercontent.com/16634089/31850347-7147422c-b661-11e7-9f61-8913cbe84e56.png">

`quoteleft` and `quoteright`, `quotesinglbase`

<img width="471" alt="screen shot 2017-10-21 at 1 13 58 pm" src="https://user-images.githubusercontent.com/16634089/31850368-c612be80-b661-11e7-863a-660acffce8d3.png">

By looking at `comma` this seems more like a feature than a bug. Masters are incompatible and different by definition.

<img width="351" alt="screen shot 2017-10-21 at 1 15 16 pm" src="https://user-images.githubusercontent.com/16634089/31850376-e62f11d2-b661-11e7-861d-3926b615d3de.png">

**Comment by alexeiva** [comment]
<img width="352" alt="screen shot 2017-10-21 at 1 16 48 pm" src="https://user-images.githubusercontent.com/16634089/31850396-1b3c15e6-b662-11e7-9890-084554a400e2.png">

**Comment by davelab6** [comment]
I think its a bug; please fix to be like the regular :)

**Comment by alexeiva** [comment]
okay, will do in next release.

**Comment by m4rc1e** [comment]
Shall we fix this before I pr?
