### ISSUE TITLE
[Cyrillic] glyphs designed correctly?

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/AmaticSC#9]
**uni0452**
![screen shot 2017-10-24 at 16 23 12](https://user-images.githubusercontent.com/7525512/31953118-45697e1a-b8da-11e7-8ce4-560895d632e5.png)

System font looks like this
![screen shot 2017-10-24 at 16 24 18](https://user-images.githubusercontent.com/7525512/31953140-534d94ee-b8da-11e7-815e-a258496983a8.png)

There are a few of them which have this problem.

ping @alexeiva

**Comment by alexeiva** [comment]
Just to repeat here: this is an uppercase solution, which is fine for a Small Caps font.

`uni0452`
<img width="219" alt="screen shot 2017-10-26 at 11 24 41 am" src="https://user-images.githubusercontent.com/16634089/32040002-4d4618c0-ba40-11e7-8f0a-7bac2c9f1334.png">
`uni045B`
<img width="229" alt="screen shot 2017-10-26 at 11 24 53 am" src="https://user-images.githubusercontent.com/16634089/32040003-4d83a924-ba40-11e7-8dbb-9cec0e0f4f3c.png">

**Comment by m4rc1e** [comment]
Thanks, closing
